name: Update develop branch after main

on:
  push:
    branches:
      - main

env:
  GIT_USER_EMAIL: "41898282+version管理くんからの通知です@users.noreply.github.com"
  GIT_USER_NAME: "version管理くん"

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # トークンを追加

      - name: Merge main to develop
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git fetch origin develop
          git checkout develop
          git merge main --no-ff -m "Sync develop with main after changes"
          git push origin develop  # push の際にトークンを使用
        shell: bash
